// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIk5UHk_PSAxUqJw3n_zAv1ONBX8103PU',
    appId: '1:176341885852:web:9123f903ba70016c685e59',
    messagingSenderId: '176341885852',
    projectId: 'fir-note-90133',
    authDomain: 'fir-note-90133.firebaseapp.com',
    storageBucket: 'fir-note-90133.firebasestorage.app',
    measurementId: 'G-J65Q79W9N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXe8Fm698hAfWxDAW3GfRoDnYMQYyOPXY',
    appId: '1:176341885852:android:e4e25099a77e20c9685e59',
    messagingSenderId: '176341885852',
    projectId: 'fir-note-90133',
    storageBucket: 'fir-note-90133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLgQ6xuXB7xBPOK8n_Cex0iVLJ8E5ilJk',
    appId: '1:176341885852:ios:7777b688c37c2db3685e59',
    messagingSenderId: '176341885852',
    projectId: 'fir-note-90133',
    storageBucket: 'fir-note-90133.firebasestorage.app',
    iosBundleId: 'com.example.newfirebase',
  );
}
